### ISSUE TITLE
.obj

### ISSUE THREAD

**Issue by ausjad** [MorganSmolder/VaugeNameSoPeopleCantStealOurStuff#6]
Might consider changing the .gitignore so that it doesn't .obj files because we seem to be forgetting to add them manually.

(we're missing start.obj and rock.obj in master so we cant run the project without it crashing because it cant find the object)
we should probably add something to make it so it doesn't try to use the object if it failed to load.

**Comment by MorganSmolder** [comment]
Yep, its easy to forget. 

Maybe in future lets just rename our models so they have the .wobj (wavefront obj) extension. Should fix the problem.
